using System.Text;

namespace Faker.NET.RU.Lorem
{
    public static class Lorem
    {
        /// <summary>
        /// Returns a set amount of words generated by lorem ipsum
        /// </summary>
        /// <param name="words">Number of words to return</param>
        /// <returns></returns>
        public static string GetText(int words) => lorem.GetText(words);

        private static LoremIpsum lorem => new();
    }
}
