using System.Text;

namespace Faker.NET.RU.Lorem
{
    public static class Lorem
    {
        /// <summary>
        /// Returns a set amount of words generated by lorem ipsum
        /// </summary>
        /// <param name="words">Number of words to return</param>
        /// <returns></returns>
        public static string GetText(int words)
        {
            var sb = new StringBuilder();

            for (int i = 0; i < words; i++)
            {
                sb.Append($"{lorem.Get()} ");
            }

            return sb.ToString().Trim();
        }

        private static LoremIpsum lorem = new();
    }
}
