# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show dirs
      run: ls -p | grep -v / | tr '\n' ','
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ../../src/Faker.NET/Faker.NET.csproj
    - name: Build
      run: dotnet build ../../src/Faker.NET/Faker.NET.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet test ../../tests/Faker.NET.Tests/Faker.NET.Tests.csproj --no-build --verbosity normal
